behaviors:
  MovingObstaclesRaycast:
    trainer_type: ppo    
    max_steps: 1.0e7
    hyperparameters:
      batch_size: 512
      beta: 0.005
      buffer_size: 2048
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 0.0003
      num_epoch: 3
    network_settings:
      num_layers: 2
      normalize: false
      hidden_units: 128
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      # curiosity:
        # strength: 0.02
        # gamma: 0.99
        # encoding_size: 256
    # behavioral_cloning:
      # demo_path: Project/Demos/OneJumpDangerRT.demo
      # strength: 0.5      